name: Deploy Next.js app using PM2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pm2-deployment"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Install PM2 globally
        run: npm install pm2 -g

      - name: Start Next.js app using PM2
        run: |
          # Navigate to the directory where the Next.js app is built
          pm2 start npm --name "nextjs-app" -- run start

      - name: Save PM2 process list
        run: pm2 save

      - name: Upload artifact (build output)
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out  # Ensure this is the correct path where your static files are stored after next export.

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
